### PR TITLE
Add Cracking the Coding interview

### PR DESCRIPTION
**Pull request by adamliesko**

### CODE REVIEW

**Comment by jsuchal** [comment]
O diky! A recenziu rovno nemas?

**Comment by adamliesko** [comment]
ano, napisem zajtra snad.

**Comment by jsuchal** [comment]
Fajn, tak ti to tu necham otvorene a potom to dame naraz ok?

**Comment by adamliesko** [comment]
Pridal som to vcera :)

**Comment by jsuchal** [comment]
Super.

**Pull request merged**
